- package.json
This change enables us to have a .env file which points to the actual test services - rather than having to run everything locally.
> CRS-125 Enable dotenv so that environment variables can be overridden to aid with local development.

- package-lock.json
- package.json
- server/views/pages/partials/calculationSummaryBreakdown.njk
Upgraded govuk frontend to version 4.0.0.
Only display change was that `govuk-hint` is no longer display block. So had to make sure the line breaks were in place in the table. I'll let Ash know
> CRS-661 fixed to govuk version 4.

- helm_deploy/calculate-release-dates/values.yaml
- server/config.ts
- server/routes/calculationRoutes.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
Moving the GTM container id to secrets. This will stop GA loading on dev machines and allow env specific GA config (if required in the future)
> CRS-628 Moving container id to secrets.

- server/config.ts
in line with the penetration test report
An example of another project doing session timeouts from 120 minutes to 20 minutes:
https://github.com/ministryofjustice/book-a-prison-visit-staff-ui/pull/97/files
Link to the ticket being progressed: https://dsdmoj.atlassian.net/browse/CRS-798
> Set session timeout default to 20 minutes

- .circleci/config.yml
- package-lock.json
- package.json
* Bump node to 20+
* Bump npm to 10+
The above was required to move to a security patched version of some libraries.
> CRS-1664 Update packages and node version to remove vulnerabilities

- docs/development.md
* After templating changes were made this removed the include of dotenv from `config.ts`, so it now has to be set in $NODE_OPTIONS for the `.env` file to be read.
> Add note into development.md now that dotenv package is not imported

- server/@types/calculateReleaseDates/index.d.ts
- server/models/ComparisonResultOverviewModel.ts
- server/routes/compareRoutes.test.ts
* Some calculated HDCED4+ dates that were calculated were not being displayed due to them not being included in the mismatch results.
> CRS-1788 Fix HDC4+ BC plus missing dates

- server/views/pages/partials/checkInformation/adjustmentDetails.njk
* Going through the calculation view journey the adjustments are not analysed
* There may be a future change to differentiate the view to calculate journeys as the change badges perhaps are not appropriate.
> CRS-1815 Fix issue with empty analysis when looking up a calculation

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/config.ts
- server/routes/startRoutes.test.ts
- server/routes/startRoutes.ts
- server/services/userPermissionsService.test.ts
- server/services/userPermissionsService.ts
- server/views/pages/ccardIndex.njk
Added a feature toggle for CCARD layout changes and route to the new landing page if going to /?prisonId=XXXXXX, formerly known as DPS landing page, and the feature toggle is on. Turned on in dev along with DPS header
> CRS-1819 - Routes for new CCARD landing page and feature toggle

- server/app.ts
- server/middleware/setUpCCARDComponents.test.ts
- server/middleware/setUpCCARDComponents.ts
- server/routes/startRoutes.test.ts
- server/routes/testutils/appSetup.ts
- server/views/pages/ccardIndex.njk
- server/views/partials/layout.njk
If the user is CRD only and doesn't have access to adjustments then we hide the blue service banner and sub nav on the DPS landing page.
> CRS-1826: Hide subnav and blue bar if CRD only user

- integration_tests/e2e/approvedDatesPath.cy.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/pages/approvedDatesEnterDate.ts
- integration_tests/pages/approvedDatesQuestion.ts
- integration_tests/pages/approvedDatesRemoveDate.ts
- integration_tests/pages/approvedDatesSelectDatesToEnter.ts
- integration_tests/pages/calculationSummary.ts
- server/@types/calculateReleaseDates/calculateReleaseDatesClientTypes.ts
- server/api/calculateReleaseDatesApiClient.test.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/routes/approvedDatesRoutes.test.ts
- server/routes/approvedDatesRoutes.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/routes/genuineOverrideRoutes.ts
- server/routes/index.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/services/approvedDatesService.ts
- server/services/dateTypeConfigurationService.test.ts
- server/services/dateTypeConfigurationService.ts
- server/services/manualEntryService.ts
- server/testutils/createUserToken.ts
- server/views/pages/approvedDates/removeDate.njk
- server/views/pages/approvedDates/selectApprovedDates.njk
- server/views/pages/approvedDates/submitDate.njk
Get rid of full string lookup and use the reference data from the API instead. Also added integration tests to cover approved dates.
> CRS-1847: use backend for date descriptions

- server/routes/genuineOverrideRoutes.test.ts
- server/routes/genuineOverrideRoutes.ts
- server/routes/index.ts
- server/services/userInputService.ts
Was blowing up with calc reason not in session (which it never could be). Now copies calc reason from original calculation.  Also was using the old reference on calc summary which is invalid with the new calculation id.
> CRS-1875: Fix genuine overrides

- server/@types/calculateReleaseDates/index.d.ts
- server/models/SentenceAndOffenceViewModel.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/components/sds-plus-notification-banner/macro.njk
- server/views/pages/components/sds-plus-notification-banner/template.njk
- server/views/pages/genuineOverrides/checkInformation.njk
- server/views/pages/manualEntry/checkInformationUnsupported.njk
Add SDS+ notification banner on check information page if any sentence is SDS+. Also changed to use new isSDSPlus flag for SDS+ badge as using indicators was causing NOMIS flagged sentences to show as SDS+ even if they weren't SDS sentences or were too short.
> CRS-1641 & CRS-1940: SDS+ highlights

- integration_tests/e2e/happyPath.cy.ts
- integration_tests/pages/sentencesAndOffencesCommon.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/partials/checkInformation/sentenceCard.njk
- server/views/pages/partials/genuineOverrides/sentenceCard.njk
https://dsdmoj.atlassian.net/browse/CRS-1945
The following routes and relevant tests has been amended to display the Offence code with offence description
/calculation/:nomsId/check-information
/calculation/:nomsId/check-information-unsupported
/specialist-support/calculation/:calculationReference/sentence-and-offence-information /view/:calculationRequestId/sentences-and-offences
The integration test has also been amended to test for this info.
> Display Offence Code with Offence description

- helm_deploy/values-preprod.yaml
* Bulk comparison in preprod is taking a little longer to return, temporarily bumping the timeout whilst the root cause can be identified and improvements made.
> Increate timeout for calculatereleasedates api for pre-prod

- server/services/calculateReleaseDatesService.test.ts
- server/services/calculateReleaseDatesService.ts
If a rule is not displayed, such as adjusting HDCED to concurrent CRD, then a blank row was appearing with a date defaulted to today. Strip null adjustment rows before display.
> CRS-1964: Fix default row for undisplayed adjustment rules

- helm_deploy/values-alt-preprod.yaml
* Apply the same timeout to the front end as applied to preprod for bulk calc taking a while.
N.B The SDS SI analysis has been largely completed on the alt-preprod env
> Bump front end timeout for calls to CRDS API

- helm_deploy/values-prod.yaml
* Apply same CRDS API timeout bump to prod, as was applied to preprod and alt-preprod
> Bump CRDS API request timeout for slow running bulk comparison

- integration_tests/e2e/checkInformation.cy.ts
- integration_tests/pages/checkInformation.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/checkInformationRoutes.ts
- server/services/userInputService.ts
This happens when someone sends you a check-information link or you navigate using the browser functions after a session expiry. You would subsequently get an error when trying to run a calculation and be returned to the wrong place.
> Redirect check-information back to calc reason if not set

- server/views/pages/partials/printNotification/prisonerDetails.njk
This fix to avoid printing name in 2 lines.
This fix allows enough space to display the name in 1 line.
> Design adjustments

- server/routes/viewRoutes.test.ts
- server/views/pages/printNotification/printNotificationSlip.njk
Improvements.
1. Fixing title text (Release dates notification slip)
2. Enabling Calculation Reason on the landing page as well as offender and establishments print slips.
> CRS-1856-Improvements

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
* Re-enables breakdown for alt envs, whilst for other envs it remains suppressed due to recent HDC changes
> Enable breakdown in alt environments

- server/routes/manualEntryRoutes.test.ts
- server/services/manualEntryService.ts
- server/views/pages/manualEntry/manualEntry.njk
- server/views/pages/partials/calculationSummary/detailsMissingInset.njk
https://dsdmoj.atlassian.net/browse/CRS-1993
> CRS-1993 Content changes across CRDS

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
* The alt and normal envs are being switched, this was to swap the toggles for exclusion labels for SDS offences when the environments are switched.
> Switch alt and normal envs for SDS Early Release

- server/data/restClient.ts
When trying to debug an issue with bulk comparison.
The following error was displayed in CRDS - 
10:09:43.233Z  INFO Calculate Release Dates: Retry handler found Calculate release dates API API error with ECONNABORTED Timeout of 60000ms exceeded
and there is no associated failure in CRDS API.
So, Improving log messages as it is difficult to determine which url has failed and fallen into retry.
Hence adding url to the log message.
> Improving log message - To help with troubleshooting an issue

- integration_tests/e2e/happyPath.cy.ts
- integration_tests/pages/viewCalculationSummary.ts
- integration_tests/pages/viewSentencesAndOffences.ts
- server/models/ViewRouteSentenceAndOffenceViewModel.ts
- server/routes/viewRoutes.test.ts
- server/routes/viewRoutes.ts
- server/views/pages/view/calculationSummary.njk
- server/views/pages/view/sentencesAndOffences.njk
https://dsdmoj.atlassian.net/browse/CRS-2058
> CRS-2058 Changing from stepper to sub nav style pages

- server/routes/checkInformationRoutes.test.ts
- server/views/pages/partials/checkInformation/sentenceCard.njk
Reverts ministryofjustice/calculate-release-dates#788
Reverting as this change does not has Louise's approval.
> Revert "CRS-2021 Change to remove New and Updated Tags from Sent and Offence Screen"

- .circleci/config.yml
- package.json
- server/routes/calculationRoutes.test.ts
- tsconfig.json
https://dsdmoj.atlassian.net/browse/CRS-2096
Using Jest to record code coverage.
Used this as a reference - https://circleci.com/docs/code-coverage/#javascript
This commit doesn't display the code coverage html page inside the artifact tab in circleci.
We just have to click on the index.html and it will open in a separate browser tab and click on links for sub html pages [Screenshots below].
https://output.circle-artifacts.com/output/job/5aa5f06d-91ab-4352-83a2-a106e03bb7a7/artifacts/0/coverage/index.html
> CRS-2096 Add UT Code coverage

- server/models/ComparisonResultOverviewModel.ts
- server/routes/compareRoutes.ts
- Set the correct defaults in the model
- Moved the ComparisonResultOverviewModel into a variable (for easier understanding and debugging locally)
> Fixing display of historic calcs

- server/errorHandler.test.ts
- server/services/manualEntryValidationService.test.ts
- server/services/manualEntryValidationService.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/accessibility.njk
- server/views/pages/components/sds-plus-notification-banner/template.njk
- server/views/pages/error.njk
- server/views/pages/partials/complete/feedbackSection.njk
Including adding createSupportLink utility and update support link references across the application
- Introduced `createSupportLink` utility function to generate mailto links with optional subject, prefix, and suffix.
- Updated tests in `utils.test.ts` to cover various cases of `createSupportLink` usage.
- Replaced static mailto links with dynamic support links generated using `createSupportLink` in templates and error messages (e.g., `sds-plus-notification-banner`, `accessibility.njk`, and `error.njk`).
- Updated the manual entry validation service to use `createSupportLink` for consistent support link formatting.
- Modified related tests to reflect the updated support link structure in validation error messages.
> Update Email Links

- server/views/pages/partials/customErrorBanner.njk
- server/views/pages/partials/errorBanner/error-summary-default.njk
- server/views/pages/partials/errorBanner/error-summary-missing-prison-api-data.njk
- server/views/pages/partials/errorBanner/error-summary-save-dates.njk
- server/views/pages/partials/errorBanner/error-summary-suspended-offence.njk
- server/views/pages/partials/errorBanner/error-summary-unsupported-calculation.njk
- server/views/pages/partials/errorBanner/error-summary-unsupported-offence.njk
- server/views/pages/partials/errorBanner/error-summary-unsupported-sentence.njk
- server/views/pages/partials/errorBanner/error-summary-validation.njk
- server/views/pages/partials/errorBanner/error-title-default.njk
- server/views/pages/partials/errorBanner/error-title-missing-prison-api-data.njk
- server/views/pages/partials/errorBanner/error-title-save-dates.njk
- server/views/pages/partials/errorBanner/error-title-suspended-offence.njk
- server/views/pages/partials/errorBanner/error-title-unsupported-calculation.njk
- server/views/pages/partials/errorBanner/error-title-unsupported-offence.njk
- server/views/pages/partials/errorBanner/error-title-unsupported-sentence.njk
- server/views/pages/partials/errorBanner/error-title-validation.njk
- server/views/pages/partials/errorBanner/list-validation-messages.njk
- Introduced dynamic `errorKey` logic with fallback to a safe default.
- Added reusable partial `list-validation-messages.njk` to streamline validation message rendering.
- Created specific partial templates for error scenarios
- Updated `customErrorBanner.njk` to use dynamic titles and include error-specific partials.
- Simplified error summary structure for maintainability and extensibility.
Warning: I'm not sure there is full test coverage for this
> Refactor error summary handling and add partial templates for validation messages

- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/partials/checkInformation/sentenceCard.njk
If SDS40 exclusions end with _T3, exclusions is tranche three related and needs different text from the standard exclusions.
Create new njk filter to format the correct feedback.
> CRD-2203-format-t3-exclusion

- integration_tests/e2e/calculationSummary.cy.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/pages/calculationSummary.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.ts
- server/views/pages/components/calculation-summary-dates-card/CalculationSummaryDatesCard.test.ts
- server/views/pages/components/calculation-summary-dates-card/template.njk
Exclude Nomis override dates when viewing calculation summary page.
The override flag will be invalid once a calculation is confirmed and submitted to Nomis.
> CRS-1956-remove-override-hint-from-calc-summary

- helm_deploy/values-alt-dev.yaml
Add missing env values for alt-dev for audit queue
> crs-2294-alt-dev-env-audit-values

- server/@types/calculateReleaseDates/index.d.ts
- server/models/ManualEntryLandingPageViewModel.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/services/calculateReleaseDatesService.test.ts
- server/services/calculateReleaseDatesService.ts
- Extended SupportedValidationResponse to include unsupportedManualMessages
- Passed new validation messages through service, model, and route layers
- Ensured consistency with unsupportedSentence and unsupportedCalculation message
> Add support for displaying unsupportedManualMessages in manual entry journey

- assets/scss/components/_adjustments.scss
- server/views/pages/components/adjustments-tables/AdjustmentTablesModel.ts
- server/views/pages/components/adjustments-tables/adjustmentTables.test.ts
- server/views/pages/components/adjustments-tables/template.njk
Adjust column sizes, changed wording of unused deductions and moved the recall tag to the middle column for tagged bail.
> CRS-2449: New adjustments UI - small tweaks

- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/services/manualEntryService.ts
If no dates are saved within the session, redirect to select dates page.
Covers scenarios where session data expires or a save function failed.
> crs-2448-ensure-dates-on-confirmation-page
