ministryofjustice/calculate-release-dates

- helm_deploy/values-dev.yaml
- integration_tests/pages/index.js
- server/@types/prisonApi/prisonClientTypes.ts
- server/@types/prisonerOffenderSearch/prisonerSearchClientTypes.ts
- server/api/prisonApiClient.test.ts
- server/api/prisonApiClient.ts
- server/api/prisonerSearchApiClient.ts
- server/api/restClient.ts
- server/config.ts
- server/routes/index.test.ts
- server/routes/index.ts
- server/routes/otherRoutes.test.ts
- server/routes/otherRoutes.ts
- server/services/prisonerService.ts
- server/views/pages/index.njk
- server/views/pages/partials/prisonerSearch.njk
- server/views/pages/partials/prisonerSearchTable.njk
- server/views/pages/prisoners.njk
TODO's
- the screens aren't as per the design so are lacking unit / integration tests (this will be done later)
- Add restriction to searching prisoners so it only looks at the prisons that the user has access to (will be a separate ticket)
https://user-images.githubusercontent.com/3595969/127884286-ee8b7f33-b22c-42a8-83fd-cdd94e495dcc.mp4
> CRS-125 Integrate the prisoner search service and create some rudimentary screens for our service

- README.md
- package-lock.json
- package.json
Fix to package.json and readme
> Crs 180 npm security update

- server/@types/prisonApi/prisonClientTypes.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/api/prisonApiClient.ts
- server/routes/otherRoutes.ts
- server/services/calculateReleaseDatesService.ts
- server/services/prisonerService.ts
- server/views/pages/partials/prisonerSearchTable.njk
- server/views/pages/partials/sentenceAdjustmentsTable.njk
- server/views/pages/partials/sentenceTermsTable.njk
- server/views/pages/prisonerDetail.njk
Has exposed some issues with our data mapping between prison-api and CRD - will look into that next
https://user-images.githubusercontent.com/3595969/130205519-756d2092-b55f-4c96-b67a-0e0276bb7196.mp4
> CRS-206 Add prisoner calculation section to prisoner details screen + call api to run calculation for a prisoner

- .circleci/config.yml
- Dockerfile
- package-lock.json
- package.json
The docker caching fix was copied from a change to the template project
https://github.com/ministryofjustice/hmpps-template-typescript/pull/49
> CRS-324 Change alerts channel + fix docker caching issue + upgrade sass

- README.md
- integration_tests/integration/login.spec.js
- integration_tests/pages/index.js
- package-lock.json
- server/views/pages/index.njk
https://user-images.githubusercontent.com/3595969/132253004-34bf0811-6ea3-4fd6-bf4e-82aa3086bb1e.mp4
> CRS-266 Change landing page to match the latest design

- integration_tests/integration/login.spec.js
- server/views/partials/header.njk
- server/views/partials/layout.njk
https://user-images.githubusercontent.com/3595969/132333592-7ca6c00b-2b36-47f9-8827-6c77d475dfb0.mp4
> CRS-320 Add a phase banner to the common layout page

- feature.env
- integration_tests/integration/checkInformation.spec.js
- integration_tests/integration/login.spec.js
- integration_tests/mockApis/prisonApi.js
- integration_tests/pages/checkInformation.js
- integration_tests/pages/page.js
- integration_tests/plugins/index.js
- package.json
- server/routes/otherRoutes.ts
- server/views/pages/calculation/checkInformation.njk
Planning to have an e2e int test (similar to CVL) - that will; be done once we have more screens in place
> CRS-269 add small int test for check information screen

- server/middleware/setUpWebSecurity.ts
- server/views/partials/layout.njk
GTM scripts.
Using content security policy - https://developers.google.com/tag-manager/web/csp
Copied from https://github.com/ministryofjustice/hmpps-welcome-people-into-prison-ui
> CRS-443 google analytics implementation.

- feature.env
- integration_tests/integration/calculationComplete.spec.ts
- integration_tests/integration/calculationSummary.spec.ts
- integration_tests/integration/checkInformation.spec.ts
- integration_tests/integration/login.spec.ts
- integration_tests/integration/prisonerSearch.spec.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/mockApis/prisonApi.ts
- integration_tests/mockApis/prisonerSearchApi.ts
- integration_tests/pages/authSignIn.ts
- integration_tests/pages/calculationComplete.ts
- integration_tests/pages/calculationSummary.ts
- integration_tests/pages/checkInformation.ts
- integration_tests/pages/index.ts
- integration_tests/pages/page.ts
- integration_tests/pages/prisonerSearch.ts
- integration_tests/plugins/index.ts
- server/views/pages/calculation/calculationComplete.njk
- server/views/pages/calculation/calculationSummary.njk
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/calculation/printCalculationSummary.njk
- server/views/pages/index.njk
- server/views/pages/partials/calculationSummaryDates.njk
- server/views/pages/partials/prisonerSearch.njk
- server/views/pages/partials/prisonerSearchTable.njk
- server/views/pages/search/searchPrisoners.njk
- server/views/partials/layout.njk
Missing cypress test pages
Refactor page to use pageId.
> CRS-517 missing cypress test pages and refactor page to use pageId.

- integration_tests/integration/checkInformation.spec.ts
- integration_tests/integration/happyPath.spec.ts
- integration_tests/integration/prisonerSearch.spec.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/pages/calculationComplete.ts
- integration_tests/pages/checkInformation.ts
- integration_tests/pages/prisonerSearch.ts
- integration_tests/plugins/index.ts
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/partials/prisonerSearchTable.njk
Happy path end to end cypress tests.
> CRS-520 Happy path end to end tests.

- server/@types/calculateReleaseDates/calculateReleaseDatesClientTypes.ts
- server/@types/calculateReleaseDates/index.d.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/routes/calculationRoutes.test.ts
- server/routes/calculationRoutes.ts
- server/routes/index.ts
- server/services/calculateReleaseDatesService.test.ts
- server/services/calculateReleaseDatesService.ts
- server/views/pages/calculation/calculationSummaryBreakdown.njk
- server/views/pages/partials/breakdownDate.njk
- server/views/pages/partials/calculationSummaryBreakdown.njk
Proof of concept for calculation breakdown.
> CRS-538 Breakdown POC.

- integration_tests/integration/checkInformation.spec.ts
- integration_tests/mockApis/prisonApi.ts
- integration_tests/pages/checkInformation.ts
- server/@types/prisonApi/index.d.ts
- server/routes/calculationRoutes.test.ts
- server/routes/calculationRoutes.ts
- server/utils/utils.ts
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/partials/sentenceTable.njk
Display court case and line sequence in check nomis screen.
> CRS-467 displaying court case and line sequence in check nomis screen.

- server/@types/calculateReleaseDates/ErrorResponse.ts
- server/@types/calculateReleaseDates/GovUkError.ts
- server/middleware/flashMessageMiddleware.ts
- server/routes/calculationRoutes.ts
- server/routes/otherRoutes.ts
- server/utils/errorUtils.ts
- server/utils/utils.ts
> CRS-466 display line breaks in error messages.

- server/routes/otherRoutes.ts
- server/views/pages/test-pages/testCalculation.njk
This is part of of a temprary screen just to aid testing of the calculation algorithm. Therefore take coding standards with a pinch of salt (i.e. no unit tests and some eslint disabling).
> CRS-648 Add ESED to bulk comparison test screen that checks calculation differences between NOMIS and CRD

- server/views/pages/partials/calculationSummary/detailsMissingInset.njk
- server/views/pages/partials/calculationSummary/howDatesCalculatedInset.njk
- server/views/pages/partials/calculationSummaryDates.njk
- Reorder insets and put inside partials
- Change the order of HDC and TUSED
> Crs 649 replace inset

- server/views/pages/index.njk
- server/views/pages/partials/prisonerIdentityBar.njk
- rename the offender
- change the content to match the ticket
> Add the prisoner identity bar to the start page

- integration_tests/pages/prisonerSearch.ts
- server/routes/searchRoutes.test.ts
- server/views/pages/partials/prisonerSearch.njk
- server/views/pages/partials/prisonerSearchTable.njk
- server/views/pages/search/searchPrisoners.njk
- Move the prison number to the start
- Remove the image column
- remove the check nomis information button
- add the govuk-link class
- add in the text "You can search using a person’s name or prison number."
> Match the design to the prototype

- server/views/pages/calculation/calculationComplete.njk
> Add in the prisoner identity bar

- assets/sass/local.sass
Tweak to the appearance of the identification bar
> Adjust the identity bar to reduce the padding

- server/routes/testutils/appSetup.ts
- server/services/userService.ts
- server/utils/nunjucksSetup.ts
- server/views/partials/layout.njk
This has roughly copied what CVL have done. However we're only adding caseloads to data layer.
> CRS-698 populating GA data later.

- server/views/pages/partials/calculationSummaryDates.njk
Change the Top up supervision end date  to Top up supervision expiry date
> Change Top up supervision end date to Top up supervision expiry date

- package-lock.json
- package.json
Amend the compile-sass command
> Add the MOJ Frontend package

- server/@types/prisonApi/PrisonApiOffenderKeyDates.ts
- server/api/prisonApiClient.ts
- server/routes/otherRoutes.ts
- server/services/prisonerService.ts
> CRS-855 comparing ESL and JSL.

- server/routes/checkInformationRoutes.test.ts
- server/routes/checkInformationRoutes.ts
Bug where multiple offences were breaking the code which checked if all questions had been answered before allowing the user to continue to the calculation
> CRS-949 fixed bug with multiple offences.

- .circleci/config.yml
This PR adding Circle CI integration with JIRA. Check if any extra config needed in circle CI: From this thread
https://mojdt.slack.com/archives/C012FNNQ4A3/p1646210325451589
> CRS-989 updating orb.

- assets/sass/_local.scss
- server/models/SentenceTypes.ts
- server/views/pages/calculation/calculationSummary.njk
- server/views/pages/partials/ersedRecallNotificationBanner.njk
* CRS-1172 Typo in standardRecallSentenceTypes
* CRS-1173 Fix notice banner rendering
> ERSED front end bugs

- server/routes/index.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/views/pages/manualEntry/manualEntry.njk
https://github.com/ministryofjustice/calculate-release-dates/assets/3595969/c3d81c03-3ecf-45f9-b9e9-4bf7f39180d0
> CRS-1399 Add first draft of manual entry start page - will be used for manually entering release dates for unsupported sentences

- server/views/pages/manualEntry/manualEntry.njk
> CRS-1399 Modify contents on new manual entry page

- server/routes/approvedDatesRoutes.test.ts
- server/routes/approvedDatesRoutes.ts
- server/routes/calculationRoutes.test.ts
- server/routes/index.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/services/dateValidationService.ts
- server/services/index.ts
- server/services/manualEntryService.ts
- server/views/pages/approvedDates/approvedDatesQuestion.njk
- server/views/pages/approvedDates/submitDate.njk
* Refactor manual entry
* Add some more tests
> CRS-1534 Allow entry of approved dates

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/config.ts
First PR for implementing DPS Banner - introduction of feature toggle
> CRS-1648 - Add feature toggle config

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/config.ts
* Feature toggle added
* Set false for all enviroments
> CRS-1694 Add a feature toggle to add a Reason for Calculation feature

- server/models/ComparisonResultMismatchDetailModel.ts
- server/views/pages/compare/manualResultDetail.njk
- server/views/pages/compare/releaseDatesMismatchTable.njk
- server/views/pages/compare/resultDetail.njk
This also moves releaseDatesMismatchTable into a component
> Introduce new mismatch column 

- server/models/ComparisonResultMismatchDetailModel.ts
- server/views/pages/compare/resultDetail.njk
> Fix to the release dates table

- docs/release-date-types.md
> Update release-date-types.md for MTD

- server/@types/calculateReleaseDates/index.d.ts
- server/models/ComparisonResultMismatchDetailModel.ts
- server/views/pages/compare/manualResultDetail.njk
- server/views/pages/compare/resultDetail.njk
* Add SDS plus sentences to bulk comparison detail pages
> CP-1670 Add identified SDS+ Sentences Offences to BC

- assets/js/autoCompletePrisonName.js
- assets/sass/_local.scss
- assets/sass/application.sass
- package-lock.json
- package.json
- server/middleware/setUpStaticResources.ts
- server/routes/compareRoutes.ts
- server/views/pages/compare/list.njk
- server/views/pages/compare/list/comparisonListItem.njk
- server/views/pages/compare/manualList.njk
- server/views/pages/compare/resultOverview.njk
- server/views/partials/layout.njk
- Include a filter by prison
- Add tabs to filter by yours, or others comparisons
> Various changes to the improve the functionality of the listing pages

- server/views/pages/compare/list.njk
- server/views/pages/compare/resultOverview.njk
- Change to use a link and a button group
- show counts on tabs
> 2 small design tweaks

- server/routes/startRoutes.ts
- server/views/pages/index.njk
Fixed DPS route so reason is always requested if enabled
> Fixed DPS route so reason is always displayed

- server/routes/calculationQuestionRoutes.test.ts
- server/routes/calculationQuestionRoutes.ts
- server/views/pages/calculation/reason.njk
Front end changes following review
> Design tweaks to template

- server/models/SentenceTypes.ts
* Add missing sentence type 14FTRHDC_ORA to fix prod issue
> Bug fix prod add missing sentence type 14FTRHDC_ORA

- server/@types/calculateReleaseDates/index.d.ts
Output of the type generation sctipt hadn't been fully titied/integrated.
> Tidied up index.

- server/@types/express/index.d.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/data/hmppsAuthClient.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/checkInformationRoutes.ts
- server/services/calculateReleaseDatesService.ts
- server/services/checkInformationService.ts
* Add a new validation method for use prior to manual entry
> CRS-1634 Validate Nomis Offence Dates before proceeding to Manual Entry Screen

- package-lock.json
- package.json
- server/models/CommonElementConfig.ts
- server/models/CommonLayoutViewModel.test.ts
- server/models/CommonLayoutViewModel.ts
- server/routes/startRoutes.test.ts
- server/views/pages/ccardIndex.njk
Currently assumes you have access to adjustments as well. That'll be fixed in CRS-1826
> CRS-1819 - add sub nav and action card to ccard landing page

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- integration_tests/e2e/approvedDatesPath.cy.ts
- integration_tests/e2e/happyPath.cy.ts
- integration_tests/e2e/manualDatesPath.cy.ts
- server/config.ts
- server/routes/calculationRoutes.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/calculation/calculationComplete.njk
- server/views/pages/partials/complete/calculationSavedCalculated.njk
- server/views/pages/partials/complete/feedbackSection.njk
> CMG-39 Some design changes to the Calculation Complete main screen

- .circleci/config.yml
- helm_deploy/values-alt-dev.yaml
- Changes to add a new Frontend environment
> Add a new alternative frontend environment

- server/routes/calculationRoutes.test.ts
- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/calculation/calculationComplete.njk
> CMG-125 Change content on calculation complete screen (involves pluralising prisoners name)

- server/@types/calculateReleaseDates/calculateReleaseDatesClientTypes.ts
- server/@types/calculateReleaseDates/index.d.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/models/ViewRouteSentenceAndOffenceViewModel.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/routes/viewRoutes.test.ts
- server/services/viewReleaseDatesService.ts
Use new flag for SDS+ on view journey and update types to reflect actual API
> CRS-1940: Fix SDS+ badge on view journey

- server/views/pages/components/sds-plus-notification-banner/template.njk
Add contact details for when SDS+ has been identified incorrectly.
> CRS-1959: SDS+ notification banner update

- integration_tests/e2e/approvedDatesPath.cy.ts
- integration_tests/e2e/calculationComplete.cy.ts
- integration_tests/e2e/happyPath.cy.ts
- server/models/CalculationCompleteViewModel.ts
- server/routes/calculationRoutes.test.ts
- server/routes/calculationRoutes.ts
- server/services/calculateReleaseDatesService.test.ts
- server/services/calculateReleaseDatesService.ts
- server/views/pages/calculation/calculationComplete.njk
https://dsdmoj.atlassian.net/browse/CRS-1974
> Restrict Print Notification Slip for prisoner with indeterminate sentences

- server/routes/calculationRoutes.test.ts
- server/routes/index.ts
* Re-add printCalcSummary calculation route
> CRS-1983 Re-add routing for print calc summary calculation route

- server/@types/calculateReleaseDates/index.d.ts
- server/models/ComparisonResultOverviewModel.ts
- server/models/ListComparisonViewModel.ts
- server/routes/compareRoutes.test.ts
- server/views/pages/compare/list/comparisonListItem.njk
- server/views/pages/compare/manualResultOverview.njk
- server/views/pages/compare/resultOverview.njk
Add a count of the prisoners whose comparison failed, if any, to the list and overview pages.
> CRS-1982: Report failed comparisons

- server/models/ViewRouteSentenceAndOffenceViewModel.test.ts
- server/models/ViewRouteSentenceAndOffenceViewModel.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/partials/printNotification/adjustmentsTable.njk
https://dsdmoj.atlassian.net/browse/CRS-1987
> Fixes to "Adjustment" section of notification slips

- server/models/PrintNotificationSlipViewModel.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/printNotification/printNotificationSlip.njk
https://dsdmoj.atlassian.net/browse/CRS-1969
> HDCED text update

- server/models/KeyDate.ts
- server/models/KeyDates.ts
- server/models/PrintNotificationSlipViewModel.test.ts
- server/models/PrintNotificationSlipViewModel.ts
- server/routes/viewRoutes.test.ts
- server/routes/viewRoutes.ts
- server/views/pages/partials/printNotification/keyDates.njk
- server/views/pages/printNotification/printNotificationSlip.njk
https://dsdmoj.atlassian.net/browse/CRS-1962
Separation of DTO and NonDTO dates and displaying dates in correct order.
> CRS-1962  DTO & Non DTO Key Dates Separation

- assets/scss/_print.scss
- server/routes/viewRoutes.test.ts
- server/views/pages/printNotification/printNotificationSlip.njk
https://dsdmoj.atlassian.net/browse/CRS-1975
> CRS-1975 Print Slip Design Adjustments

- helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/CRS-2007
> CRS-2007 Enable Print Notification slip in Prod

- server/routes/approvedDatesRoutes.test.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/approvedDates/approvedDatesQuestion.njk
- server/views/pages/approvedDates/removeDate.njk
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/manualEntry/checkInformationUnsupported.njk
- server/views/pages/manualEntry/removeDate.njk
- server/views/pages/partials/checkInformation/adjustmentDetails.njk
- server/views/pages/partials/checkInformation/calculateDates.njk
- server/views/pages/partials/checkInformation/calculateDatesUnsupported.njk
- server/views/pages/view/nomisCalculationSummary.njk
- server/views/pages/view/sentencesAndOffences.njk
https://dsdmoj.atlassian.net/browse/CRS-1985
> CRS-1985 Remove name from title and question since there is mini profile displayed

- server/views/pages/partials/calculationSummary/summarySection.njk
- server/views/pages/view/nomisCalculationSummary.njk
https://dsdmoj.atlassian.net/browse/CRS-1977
Bug fix to increase to the desired font size.
> CRS-1977 Design Bug fix

- server/views/pages/partials/calculationSummary/hdc4NotificationBanner.njk
* Minor tweak to hdc4+ banner content
> CRS-2010-hdc4-banner-content

- helm_deploy/values-prod.yaml
> Enable hdced4 banner in prod

- assets/scss/_notification-slip.scss
- assets/scss/_print.scss
- assets/scss/application.scss
- server/routes/viewRoutes.test.ts
- server/views/pages/partials/printNotification/adjustmentsTable.njk
- server/views/pages/partials/printNotification/prisonerDetails.njk
- server/views/pages/partials/printNotification/sentenceTable.njk
- server/views/pages/printNotification/printNotificationSlip.njk
https://dsdmoj.atlassian.net/browse/CRS-1998
> CRS-1998 Design Improvements for PRDNS

- server/routes/viewRoutes.test.ts
- server/views/pages/printNotification/printNotificationSlip.njk
https://dsdmoj.atlassian.net/browse/CRS-1998
Design fixes where only DTO dates are available.
> CRS-1998 - Design fixes

- server/views/pages/partials/calculationSummary/hdc4NotificationBanner.njk
* Now the HDC Policy framework doc has been updated, update the link to be that of the PDF in the HDCED banner
> CRS-2010 Update HDC policy framework link for banner

- integration_tests/e2e/manualDatesPath.cy.ts
- server/routes/manualEntryRoutes.test.ts
- server/views/pages/manualEntry/dateEntry.njk
https://dsdmoj.atlassian.net/browse/CRS-2022
> CRS-2022 Remove Date Desc for Manual Entry

- integration_tests/e2e/approvedDatesPath.cy.ts
- server/routes/approvedDatesRoutes.test.ts
- server/views/pages/approvedDates/removeDate.njk
- server/views/pages/approvedDates/submitDate.njk
- server/views/pages/components/approved-summary-dates-card/template.njk
https://dsdmoj.atlassian.net/browse/CRS-2026
> CRS-2026 Remove Description for approved dates journey

- server/routes/viewRoutes.test.ts
- server/views/pages/partials/calculationSummaryBreakdown.njk
- server/views/pages/view/calculationSummary.njk
https://dsdmoj.atlassian.net/browse/CRS-2023
> CRS-2023 Design Adjustments for Calculation Summary

- server/models/CalculationSummaryViewModel.ts
- server/models/SentenceAndOffenceViewModel.ts
- server/models/SentenceTypes.ts
- server/models/ViewRouteSentenceAndOffenceViewModel.ts
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/components/ersed-checkbox/macro.njk
- server/views/pages/components/ersed-checkbox/template.njk
- server/views/pages/genuineOverrides/checkInformation.njk
- server/views/pages/partials/checkInformation/calculateDates.njk
- server/views/pages/partials/ersedRecallNotificationBanner.njk
- server/views/pages/view/sentencesAndOffences.njk
https://dsdmoj.atlassian.net/browse/CRS-1984
> CRS-1984 Move checkbox near calculate button

- helm_deploy/values-alt-dev.yaml
- server/config.ts
- server/routes/startRoutes.test.ts
- server/views/pages/ccardIndex.njk
- server/views/pages/components/sds40-policy-banner/macro.njk
- server/views/pages/components/sds40-policy-banner/template.njk
* Add banner inline with https://dsdmoj.atlassian.net/browse/CRS-2052
> CRS-2052 Add message for SDS 24 changes

- server/routes/startRoutes.test.ts
- server/views/pages/components/sds40-policy-banner/template.njk
* Change in content as requested.
> CRS-2052 SDS40 banner content update

- server/routes/approvedDatesRoutes.test.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/approvedDates/approvedDatesQuestion.njk
- server/views/pages/approvedDates/selectApprovedDates.njk
- server/views/pages/calculation/calculationSummary.njk
- server/views/pages/calculation/checkInformation.njk
- server/views/pages/manualEntry/checkInformationUnsupported.njk
- server/views/pages/manualEntry/confirmation.njk
- server/views/pages/manualEntry/dateEntry.njk
- server/views/pages/manualEntry/dateTypeSelection.njk
- server/views/pages/manualEntry/manualEntry.njk
- server/views/pages/manualEntry/noDatesConfirmation.njk
- server/views/pages/manualEntry/removeDate.njk
- server/views/pages/view/calculationSummary.njk
https://dsdmoj.atlassian.net/browse/CRS-1989
> CRS-1989 Correct back links for calc summary and standard calc

- scripts/generate-calculate-release-dates-api-types.sh
- server/@types/calculateReleaseDates/index.d.ts
- server/models/CalculationSummaryViewModel.test.ts
- server/models/CalculationSummaryViewModel.ts
- server/routes/calculationRoutes.test.ts
- server/views/pages/partials/calculationSummary/summarySection.njk
* Add tranche label to calculation summary page
* Regenerate TS types, there are a few unrelated to this change
> CRS-2056 Add SDS40 tranche label

- server/models/CalculationSummaryViewModel.test.ts
- server/models/CalculationSummaryViewModel.ts
- server/views/pages/partials/calculationSummary/summarySection.njk
* After discussion update the wording used in the tranche labels
* Minor tidy up of references to early.
> CRS-2056 Update tranche label wording

- server/routes/checkInformationRoutes.test.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/views/pages/partials/checkInformation/sentenceCard.njk
- server/views/pages/partials/genuineOverrides/sentenceCard.njk
https://dsdmoj.atlassian.net/browse/CRS-2061
> CRS-2061 Show SDS exclusions for single sentence

- server/models/CalculationSummaryViewModel.ts
- server/routes/calculationRoutes.test.ts
- server/views/pages/partials/calculationSummary/summarySection.njk
* Hide tranche label when tranche is TRANCHE_0 as per updated A/C
> CRS-2065 Don't add tranche label when tranche is TRANCHE_0

- integration_tests/e2e/manualDatesPath.cy.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- server/api/calculateReleaseDatesApiClient.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/services/manualCalculationService.ts
* Only if a recall sentence is present and the type is unsupported can manual calc be used
Early viewing
> Update manual calc validation to check for recalls

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- server/config.ts
- server/models/CalculationSummaryViewModel.ts
- server/routes/calculationRoutes.test.ts
* Also gets the env config ready for alt envs to be SDS40 enabled
> Hide tranche labels

- server/views/pages/partials/checkInformation/sentenceCard.njk
- server/views/pages/partials/genuineOverrides/sentenceCard.njk
Update label to use SDS40 terminology
> Update SDS Exclusions label

- server/views/pages/view/sentencesAndOffences.njk
https://dsdmoj.atlassian.net/browse/CRS-2058
> CRS-2058 Design fixes - Amend to use the margin from the class

- server/views/pages/partials/customErrorBanner.njk
https://dsdmoj.atlassian.net/browse/CRS-2084
Adding in changes to make "reload this page" as a hypelink.
Did a quick check in the backend to make sure there are no other validation messages with "reload this page" text.
> CRS-2084 - Make reload this page as a hyperlink

- server/routes/checkInformationRoutes.test.ts
- server/views/pages/partials/checkInformation/sentenceCard.njk
https://dsdmoj.atlassian.net/browse/CRS-2021
> CRS-2021 Change to remove New and Updated Tags from Sent and Offence Screen

- package-lock.json
- package.json
- server/models/CommonElementConfig.ts
- server/models/CommonLayoutViewModel.test.ts
- server/models/CommonLayoutViewModel.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/partials/prisonerIdentityBar.njk
+ upgrade of ccard-design-system fixes problem with latest calc card
> CMG-171 Add profile banner for prisoners that are OUT 

- server/models/ComparisonResultMismatchDetailJsonModel.ts
- server/routes/compareRoutes.ts
- server/services/calculateReleaseDatesService.ts
- server/views/pages/compare/resultJson.njk
Change view json page formatting in response to user feedback.
> CRD-2182-view-json-person-comparison

- server/services/manualEntryService.ts
Use createSupportLink function to correctly wrap error messages with supporting text.
> CRS-2191-error-message-amendments

- assets/scss/local.scss
- integration_tests/e2e/happyPath.cy.ts
- integration_tests/e2e/view.cy.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/pages/CCARDLandingPage.ts
- server/routes/viewRoutes.test.ts
- server/views/pages/ccardIndex.njk
- server/views/pages/partials/calculationSummary/minimalCalculationCard.njk
- server/views/pages/partials/calculationSummary/summary.njk
- server/views/pages/search/searchPrisoners.njk
- server/views/pages/view/calculationSummary.njk
- server/views/pages/view/nomisCalculationSummary.njk
- server/views/pages/view/sentencesAndOffences.njk
Implement UI changes inline with UI prototype.
Ensure integration tests run against CRS calculation.
> Crs 2235 highlight manual journey

- integration_tests/e2e/happyPath.cy.ts
- integration_tests/pages/CCARDLandingPage.ts
- server/views/pages/ccardIndex.njk
- server/views/pages/partials/calculationSummary/summary.njk
Fix error with latest calculation date being set to today's date, due to a null value being used against the filter,
Add integration tests to assert the expected values.
> CRS-2235-fix-calculation-date

- integration_tests/e2e/happyPath.cy.ts
- integration_tests/pages/viewCalculationSummary.ts
- server/views/pages/components/calculation-summary-dates-card/CalculationSummaryDatesCard.test.ts
- server/views/pages/components/calculation-summary-dates-card/macro.njk
- server/views/pages/components/calculation-summary-dates-card/template.njk
- server/views/pages/components/calculation-summary-dates-card/test_pre_calc.njk
- server/views/pages/partials/calculationSummary/summarySection.njk
Add additional isPreCalc option to calculationSummaryDatesCard.
Macro is used by multiple pages where a precalc can be present.
> CRS-1956-summary-section-precalc

- server/models/CheckInformationViewModel.ts
- server/routes/checkInformationRoutes.ts
- server/routes/genuineOverrideRoutes.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/partials/checkInformation/sentencesAndOffences.njk
https://dsdmoj.atlassian.net/browse/ADJST-403
> ADJST-403 - Add adjustments service link in check information page

- helm_deploy/calculate-release-dates/values.yaml
- helm_deploy/values-dev.yaml
- package-lock.json
- package.json
- server/api/calculateReleaseDatesApiClient.test.ts
- server/errorHandler.test.ts
- server/routes/approvedDatesRoutes.test.ts
- server/routes/calculationQuestionRoutes.test.ts
- server/routes/calculationRoutes.test.ts
- server/routes/calculationRoutes.ts
- server/routes/checkInformationRoutes.test.ts
- server/routes/genuineOverrideRoutes.test.ts
- server/routes/genuineOverrideRoutes.ts
- server/routes/manualEntryRoutes.test.ts
- server/routes/startRoutes.test.ts
- server/routes/viewRoutes.test.ts
- server/services/auditService.ts
- server/services/calculateReleaseDatesService.test.ts
- server/services/calculateReleaseDatesService.ts
- server/services/index.ts
Audit new calculations.
Audit any calculation failures.
> Crs 2294 audit calculations

- helm_deploy/calculate-release-dates/values.yaml
Add service account name to helm chart.
> crs-2294-add-service-name-to-chart

- server/services/auditService.ts
Always use JSON string for Audit detail.
> crs-2324-use-json-for-audit-error

- server/services/auditService.ts
Use JSON stringify in place of templated string.
> crs-2324-json-stringify-audit-calc

- server/routes/manualEntryRoutes.test.ts
- server/routes/manualEntryRoutes.ts
- server/routes/viewRoutes.test.ts
- server/routes/viewRoutes.ts
If no manual calculation reason is found, display "Not specified"
On saving new Manual Calculation, redirect to select reason page if reasonId is missing.
> crs-2320-no-reason-error

- package-lock.json
- package.json
- server/data/index.ts
- server/routes/checkInformationRoutes.ts
- server/routes/genuineOverrideRoutes.ts
- server/routes/manualEntryRoutes.ts
- server/services/manualEntryService.ts
- tsconfig.json
Allow NPM version 10 or 11.
Check POST body is NULL. Express version 4 used an empty object inplace of NULL.
> upgrade-express-version-5

- server/utils/nunjucksSetup.ts
- server/views/pages/partials/genuineOverrides/adjustmentDetails.njk
https://dsdmoj.atlassian.net/browse/ADJST-614
> ADJST-614 Display date not entered when no date is present for remand

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-dev.yaml
- server/routes/thingsToDoInterceptRoutes.test.ts
https://dsdmoj.atlassian.net/browse/ADJST-404
> ADJST-404 Move to the new Adjsutments UI Url

- server/views/pages/manualEntry/manualEntry.njk
and unsupportedManualMessages under a single heading in manual entry UI
> Combine unsupportedCalculationMessages

- server/services/prisonerService.test.ts
- server/services/prisonerService.ts
- server/utils/caseloads.test.ts
- server/utils/caseloads.ts
Using the enum to avoid making the same mistake again. 
Updating relevant tests
> CRS 2376 Fixing the name of the role to include the prefix 

- server/views/pages/calculation/consecutiveConcurrentSentences.njk
Remove copy in response to user feedback.
> crs-2395-update-multiple-consec-message

- .circleci/config.yml
- .github/workflows/deploy_to_env.yml
- .github/workflows/pipeline.yml
- helm_deploy/calculate-release-dates/values.yaml
Setup of initial pipeline and move deploy to dev & alt-dev to github actions.
> CRS-2399: Initial github actions migration

- package-lock.json
- server/@types/prisonApi/index.d.ts
- server/models/CommonLayoutViewModel.test.ts
- server/models/PrintNotificationSlipViewModel.test.ts
Update prison API type definitions.
Update NPM dependencies.
> crs-2435-update-prison-api-definitions

- server/views/pages/components/adjustments-tables/AdjustmentTablesModel.ts
- server/views/pages/components/adjustments-tables/adjustmentTables.test.ts
- server/views/pages/components/adjustments-tables/template.njk
Add ADA, UAL, LAL and Appeal Applicant adjustments to the new UI for adjustments.
> CRS-2449: New adjustments UI - additions

- integration_tests/e2e/genuineOverridePath.cy.ts
- integration_tests/mockApis/calculateReleaseDatesApi.ts
- integration_tests/pages/calculationSummary.ts
- integration_tests/pages/genuineOverrideReasonPage.ts
- integration_tests/pages/genuineOverrideReviewDatesPage.ts
- server/routes/calculation-summary/calculationSummaryController.test.ts
- server/routes/calculation-summary/calculationSummaryController.ts
- server/views/pages/calculation/calculationSummary.njk
Also started the e2e tests for genuine overrides.
> CRS-2493: Ask GO users if they agree with dates

- server/middleware/requireGenuineOverrideAccess.test.ts
- server/middleware/requireGenuineOverrideAccess.ts
- server/routes/genuine-overrides/add-date/addGenuineOverrideDateController.test.ts
- server/routes/genuine-overrides/delete-date/deleteGenuineOverrideDateController.test.ts
- server/routes/genuine-overrides/edit-date/editGenuineOverrideDateController.test.ts
- server/routes/genuine-overrides/genuineOverridesRoutes.ts
- server/routes/genuine-overrides/review-dates/reviewDatesForGenuineOverrideController.test.ts
- server/routes/genuine-overrides/select-dates/genuineOverrideSelectDatesController.test.ts
- server/routes/genuine-overrides/select-dates/genuineOverrideSelectDatesController.ts
- server/routes/genuine-overrides/select-genuine-override-reason/selectGenuineOverrideReasonController.test.ts
Make sure you can't navigate straight to the genuine override pages without the required role.
> CRS-2347: Genuine overrides enforce role

- server/models/ViewRouteSentenceAndOffenceViewModel.ts
- server/routes/viewRoutes.test.ts
- server/routes/viewRoutes.ts
…ation
Was showing undefined on the sentence and offence tab when viewing a previous calculation.
> CRS-2514: Fix OTHER calc reason description on view historical cal
